In [7]:
import numpy as np
import pandas as pd

In [2]:
x = [1, 3, 5]
y = [2,4]

In [3]:
X, Y = np.meshgrid(x, y)

In [4]:
X

array([[1, 3, 5],
       [1, 3, 5]])

In [5]:
Y

array([[2, 2, 2],
       [4, 4, 4]])

In [6]:
X * Y

array([[ 2,  6, 10],
       [ 4, 12, 20]])

In [8]:
df = pd.DataFrame(X * Y, columns=x, index=y)
df

,1,3,5
2,2,6,10
4,4,12,20
